### ISSUE TITLE
External Link is broken

### ISSUE THREAD

**Issue by renoneto** [learn-co-curriculum/dsc-intervals-with-t-distribution#2]
The following link under **Additional Resources** is broken: [https://onlinecourses.science.psu.edu/stat414/node/199/](https://onlinecourses.science.psu.edu/stat414/node/199/)

**Comment by hoffm386** [comment]
The link has been updated in https://github.com/learn-co-curriculum/dsc-intervals-with-t-distribution/commit/c0914198faf96af28bcefe7d908def61bd711752, thanks for flagging!
