### ISSUE TITLE
Wrong scale value passed to stats.t.interval

### ISSUE THREAD

**Issue by hoffm386** [learn-co-curriculum/dsc-intervals-with-t-distribution#3]
## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x] Instructions unclear
- [ ] Other (explain below)

### Source

Code:
```python
import numpy as np
sample_chol_levels = [66.0, 36.0, 73.0, 48.0, 81.0, 69.0, 75.0, 81.0, 73.0,
                      69.0, 101.0, 70.0, 50.0, 42.0, 36.0, 71.0, 65.0, 43.0, 76.0, 24.0]
x_bar = np.mean(sample_chol_levels)
s = np.std(sample_chol_levels, ddof = 1)
import scipy.stats as stats
stats.t.interval(alpha = 0.95,                              # Confidence level
                 df= len(sample_chol_levels)-1,             # Degrees of freedom
                 loc = x_bar,                               # Sample mean
                 scale = s)                                 # Standard deviation estimate
```

Explanation:
```
We then calculate our interval estimate using a t-distribution and our various parameters. The t-distribution requires 4 parameters:

The sample mean
The sample standard deviation
The degrees of freedom (this is 1 less then the number of items in the sample)
The confidence level we wish to have in our estimate
```

### Concern

Scale param in `stats.t.interval` should be the unit scale of the t-distribution, which is the standard error (`s/(len(sample_chol_levels)**0.5)`), not the standard deviation (`s`). Both code and text suggest it should be the standard deviation.

## (Optional) Proposed Solution

Rewrite code to use a different variable name, e.g. `se`, to be clearer about what is being passed in. Then pass in standard error instead of standard deviation.

**Comment by bpurdy-ds** [comment]
Eeek. This is correct.

`stats.t.interval(alpha = 0.95,                                  # Confidence level
                 df= len(sample_chol_levels)-1,                 # Degrees of freedom
                 loc = x_bar,                                   # Sample mean
                 scale = s/np.sqrt(len(sample_chol_levels)))    # Standard deviation estimate`

**Comment by bpurdy-ds** [comment]
Also, a deprecation warning for the use of `alpha`, so need to change that to `confidence`, i.e.

`stats.t.interval(confidence = 0.95,                                  # Confidence level
                 df= len(sample_chol_levels)-1,                 # Degrees of freedom
                 loc = x_bar,                                   # Sample mean
                 scale = s/np.sqrt(len(sample_chol_levels)))    # Standard deviation estimate`

**Comment by bpurdy-ds** [comment]
And the second/last one as well.

`#Min and Max of Confidence Interval
stats.t.interval(confidence = 0.95,                              # Confidence level
                 df= len(sample_chol_levels)-1,             # Degrees of freedom
                 loc = x_bar,                               # Sample mean
                 scale = s/np.sqrt(len(sample_chol_levels)))   `

Any non-code chunk references to these values must be updated too.

**Comment by bpurdy-ds** [comment]
Made the changes as described above in the repo, and removed the link and two "!".
